trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.8.4
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: '6ccc03d9-7c70-4aa1-b9d3-0ad1e242916a'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHub: true
      GitHubPackages: false
      DotNetVersion: "2.2.301"
      DotNet3Version: "3.0.100-preview7-012821"
      NuGetVersion: "5.2.0"
